theme: jekyll-theme-minimal
title: maosakana profile
description: Last-updated 2019-03-09
logo: https://user-images.githubusercontent.com/25532388/54072044-b0415c80-42b8-11e9-9b2c-632ac48b11cf.png

show_downloads: https://github.com/maosakana/maosakana.github.io/files/2948314/MaoKozumaCV.pdf
