theme: jekyll-theme-minimal

title: maosakana profile

description: Please feel free to contact me. 

logo: https://user-images.githubusercontent.com/25532388/54070891-508f8500-42a9-11e9-8e1c-a20a6c2a272f.jpg

show_downloads: https://github.com/maosakana/maosakana.github.io/files/2948314/MaoKozumaCV.pdf

